# Default configuration resource.
# IMPORTANT: keep the placeholder [path_to_todo.md_file] exactly as shown â€” DefaultConfigCreator
# will replace it with the real path when initializing the application directory.
configuration:
  todoFilePath: [path_to_todo.md_file]
  todoItem:
    dateFormat: dd/MM/yyyy
    priority:
      symbol:
        low: +
        medium: ++
        high: +++
  reminder:
    periodFactor:
      critical: 0.25
      urgent: 0.5
    periodThreshold:
      critical: 1
      urgent: 3