# This workflow will build a package using Maven and then publish it to GitHub packages
name: Maven Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Ta permisja jest kluczowa dla GITHUB_TOKEN

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Ustawilem na 21, tak jak miales w 'with'
          distribution: 'temurin'

      - name: Create settings.xml
        run: |
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"
                        xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
                        xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0
                                            https://maven.apache.org/xsd/settings-1.0.0.xsd\">
            <servers>
              <server>
                <!-- To ID musi być takie samo jak <id> w pom.xml i server-id w setup-java -->
                <id>internal.repo</id>
                <username>\${env.GITHUB_ACTOR}</username>
                <password>\${env.GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>" > $GITHUB_WORKSPACE/settings.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        # Używamy pliku settings.xml, który stworzyliśmy w poprzednim kroku
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          # Ten token jest automatycznie przekazywany do pliku settings.xml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}