name: Maven Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Ta permisja jest kluczowa dla GITHUB_TOKEN

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 and configure Maven auth
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Ustawilem na 21, tak jak miales w 'with'
          distribution: 'temurin'
          server-id: 'internal.repo' # musi odpowiadać <id> w pom.xml
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        # setup-java wygenerował settings.xml z poświadczeniami dla server-id
        run: mvn deploy
